version: '3'
services:
  wrapper:
    image: gerbil-api-wrapper-service:latest
    build:
      context: . 
      dockerfile: Dockerfile
    network_mode: host
    environment:
      - "SERVICE_PORT=40140"
